### PR TITLE
Remove the close skyrim button and clarify the message shows while running skyrim

### PR DESCRIPTION
**Pull request by TaranRoth**
Part of operation make Lizzy (and the rest of the support team) survive the next week

### CODE REVIEW

**Comment by MattLish** [comment]
I think we can go a little further than this. We should change the message depending on what is happening and have a loading icon to show it's loading. 

We should have something like:
- "Building launch profile - this can take several minutes" - This will have no button until our operations are complete and MO2 is running.
- "Building launch profile - this can take several minutes" - When MO2 is running in the background, give a button to abort
- "Skyrim is running" - When the Skyrim.exe is running. Have a "Force close Skyrim" button.
What do you think?

**Comment by phinocio** [comment]
Did a temporary fix of simply removing the button for now and changing the wording to the same as this PR so we can solve the immediate issue now, while working on a more fancy way Matt outlined above.

**Comment by MattLish** [comment]
@TaranRoth Now we've removed the button, do you think we still need to do this or just leave it as it is and see if we get more issues?

**Comment by MattLish** [comment]
@TaranRoth can this be closed?

**Comment by MattLish** [comment]
Closing because of inactivity

**Pull request closed without merging**
