### PR TITLE
feat: detect Windows 7 and alert user about incompatibility

### LINKED ISSUE #455: Detect windows 7 and provide user with a warning

### PR DESCRIPTION
**Pull request by Campiotti**
closes #455 

Open to suggestions on how to handle this, more specifically:

- Always show the popup, only once or have it on a "cooldown" of x Days?
- Changing the Message to more specifically talk about "Universal Windows Platform applications"
- Other misc amendments.

### CODE REVIEW

**Comment by Campiotti** [comment]
image

This is how the alert looks.
Once you click OK the launcher appears with all buttons enabled as usual, nothing changed.

**Comment by MattLish** [comment]
This is probably an acceptable solution for now. 
I am curious if the only issue we have is a package we use though. There is some details here: https://github.com/Wildlander-mod/Launcher/issues/504

If we fix this issue, Windows 7 might actually work.
For clarity, I think it's just the launcher that doesn't work on 7, the game does.
Do you have a Windows 7 laptop to test this? I have an old one that I can use if needed.

**Comment by Campiotti** [comment]
Unfortunately I don't think I have any windows 7 devices anymore - I simply added an || true to the if check to get the alert to popup locally.

**Comment by MattLish** [comment]
I can dust off the old Windows 7 laptop when I get some time and give this a proper test :)
We still need to implement that other package anyway, which might fix Windows 7.

**Pull request closed without merging**
